steps:
  # Langkah pertama: Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker Image"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-app:$SHORT_SHA", "."]

  # Langkah kedua: Push Docker Image ke Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Docker Image"
    args: ["push", "gcr.io/$PROJECT_ID/my-app:$SHORT_SHA"]

  # Langkah ketiga: Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy to Cloud Run"
    args:
      - "run"
      - "deploy"
      - "my-app"
      - "--image"
      - "gcr.io/$PROJECT_ID/my-app:$SHORT_SHA"
      - "--region"
      - "us-central1" # Ubah dengan region Cloud Run yang Anda pilih
      - "--platform"
      - "managed"
      - "--allow-unauthenticated" # Jika ingin akses publik tanpa autentikasi

images:
  - "gcr.io/$PROJECT_ID/my-app:$SHORT_SHA"

timeout: "1200s" # Timeout build dalam detik (20 menit)
