steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/somatch:$SHORT_SHA'
      - '.'

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/somatch:$SHORT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'somatch' # Nama layanan Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/somatch:$SHORT_SHA'
      - '--region'
      - 'asia-southeast2' # Ganti sesuai region layanan Anda
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Hapus jika layanan Anda tidak publik

substitutions:
  _SERVICE_NAME: "somatch"
  _REGION: "asia-southeast2"

timeout: '1200s'
